### ISSUE TITLE
Nudges after a PR is merged

### ISSUE THREAD

**Issue by jsadwith** [suhailgupta03/nudge#12]
@suhailgupta03 We just recently installed Nudge Bot via Github and have found it helpful so far - thanks for building it! One issue we've noticed is that it continues to nudge even after a PR has been merged and the branch has been deleted. Do you have any workarounds or advice for how to handle this?
![Screenshot 2024-05-08 at 11 47 24 AM](https://github.com/suhailgupta03/nudge/assets/5454953/b7c09414-fa85-47e1-9400-70e7e326aee5)

**Comment by suhailgupta03** [comment]
@jsadwith Thanks for sharing this here. The workflow starts with checking the open PRs. Since the PR was already merged, the state should be changed from open. Would you be willing to share the repository name and the PR number?

**Comment by suhailga** [comment]
@jsadwith Thanks for notifying me about this issue. The domain for the nudge bot (nudgebt.app) got expired and as a result, the webhook calls from Git Hub were not reaching the server.  This resulted in PR statuses not getting updated. I have repurchased the domain and it should be working in some time.

**Comment by suhailga** [comment]
@jsadwith I verified that the domain https://nudgebt.app/ is up and available now and should be reachable by GitHub.  The issue you were facing should be fixed now. Thanks so much for sharing this here 🙏 ❤️  

Please keep on using NudgeBot. It feels awesome when this helps others. Also, feel free to add feature requests.

**Comment by jsadwith** [comment]
Thanks so much, @suhailgupta03! Appreciate the quick attention to this.

**Comment by suhailga** [comment]
@jsadwith Since some of the PRs and their statuses were not synced, you might experience issues with older PRs. All status changes, and new PRs, between May 6,2024 and May 8, 2024, will be impacted.
